# Generated by Django 5.2.6 on 2025-10-03 01:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='addtask',
            name='deadline',
            field=models.DateField(blank=True, null=True),
        ),
    ]
